name: Deploy to Remote Server via SSH

on:
  push:
    branches:
      - main  # Change to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Run remote commands over SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/html/abhiramdas99.github.io
          
          # Option 1: Pull latest changes
          git reset --hard
          git pull origin main
          
          # OR Option 2: Rollback to previous commit
          # git reset --hard HEAD~1
          # Optional: git push origin HEAD --force  (if needed)

          # If you have build step (e.g., npm run build), do it here
